[package]
name = "core"
version = "1.0.1"
authors = ["Abid Omar <contact@omarabid.com>"]
description = "The application core code"
edition = "2018"

[dependencies]
utils = { path = "../utils" }

rand = "0.8.4"
log = "0.4.14"
